app2: employee.o hourlyemployee.o salariedemployee.o main2.o
	g++ -o app2 employee.o hourlyemployee.o salariedemployee.o main2.o

employee.o: employee.cpp
	g++ -c employee.cpp

hourlyemployee.o: hourlyemployee.cpp
	g++ -c hourlyemployee.cpp

salariedemployee.o: salariedemployee.cpp
	g++ -c salariedemployee.cpp

main2.o: main2.cpp
	g++ -c main2.cpp
