app0: employee.o hourlyemployee.o salariedemployee.o main0.o
	g++ -o app0 employee.o hourlyemployee.o salariedemployee.o main0.o

employee.o: employee.cpp
	g++ -c employee.cpp

hourlyemployee.o: hourlyemployee.cpp
	g++ -c hourlyemployee.cpp

salariedemployee.o: salariedemployee.cpp
	g++ -c salariedemployee.cpp

main0.o: main0.cpp
	g++ -c main0.cpp
