app1: employee.o hourlyemployee.o salariedemployee.o main1.o
	g++ -o app1 employee.o hourlyemployee.o salariedemployee.o main1.o

employee.o: employee.cpp
	g++ -c employee.cpp

hourlyemployee.o: hourlyemployee.cpp
	g++ -c hourlyemployee.cpp

salariedemployee.o: salariedemployee.cpp
	g++ -c salariedemployee.cpp

main1.o: main1.cpp
	g++ -c main1.cpp
