app3: employee.o hourlyemployee.o salariedemployee.o main3.o
	g++ -o app3 employee.o hourlyemployee.o salariedemployee.o main3.o

employee.o: employee.cpp
	g++ -c employee.cpp

hourlyemployee.o: hourlyemployee.cpp
	g++ -c hourlyemployee.cpp

salariedemployee.o: salariedemployee.cpp
	g++ -c salariedemployee.cpp

main3.o: main3.cpp
	g++ -c main3.cpp
